### ISSUE TITLE
Unauthorized exception for docker-push-jump-host target in airship-sip-publish-images job

### ISSUE THREAD

**Issue by sshturm** [airshipit/sip#16]
**Description**
Zuul job for publishing images fails with unauthorized error for docker-push-jump-host target

**Steps To Reproduce**
Check the [airship-sip-publish-images](https://zuul.opendev.org/t/openstack/builds?job_name=airship-sip-publish-images) on merge event.

**Expected behavior**
airship-sip-publish-images completed successfully, images are available in the registry.

**Comment by teoyaomiqui** [comment]
It appears that quay.io/jump-pod is missing permission for the push user. I've added the permission, next merge the job should be successful.

**Comment by teoyaomiqui** [comment]
this can be closed, images are successfully pushed, and the job is green
https://zuul.opendev.org/t/openstack/builds?job_name=airship-sip-publish-images
https://zuul.opendev.org/t/openstack/build/549bac0536384596b95e82f19803680d
