### ISSUE TITLE
Make Load Balancer Infra Services HAProxy Configurable

### ISSUE THREAD

**Issue by lb4368** [airshipit/sip#19]
**Problem description**
Currently when applying a SIPCluster CR, the SIP controller uses hard-coded HAProxy configurations to build the load balancer infrastructure services for the API server and the workload services.  There may be situations where a different configuration is desired for one or both of the load balancers such as timeout settings and health checks. 

**Proposed change**
Provide a mechanism to customize the HAProxy configuration.  This could be done by allowing the use of custom templates referenced in the SIPCluster CR for the HAProxy configurations or by allowing individual values within the default HAProxy configuration to be overridden from within the CR.

Adding the "design needed" label for a design discussion on an approach.

**Comment by michaelfix** [comment]
@seaneagan  mentioned he may be able to pickup once the initial 2.1 commitments are closed.

**Comment by manojkva** [comment]
Please assign this to me

**Comment by manojkva** [comment]
I could pick this up if @seaneagan  has not started it.

**Comment by eak13** [comment]
@manojkva all yours.

**Comment by manojkva** [comment]
PS = https://review.opendev.org/c/airship/sip/+/799161
