### ISSUE TITLE
Add Jump Host Liveness and Readiness Probes

### ISSUE THREAD

**Issue by drewwalters96** [airshipit/sip#6]
**Problem description (if applicable)**
If the Jump Host SSH daemon stops functioning but the container continues to run, cluster operators will not know and SSH access to the corresponding sub-cluster will be interrupted.

**Proposed change**
Add liveness (and readiness) probes to the SSH endpoint so that SSH service can be restored.

Depends on the completion of the [SSH daemon](https://review.opendev.org/c/airship/sip/+/77809).

**Comment by matthew-fuller** [comment]
Please assign this to me.

**Comment by matthew-fuller** [comment]
I don't know if this repo has a bot configured, so here's the PS for this issue:
https://review.opendev.org/c/airship/sip/+/792704
