### ISSUE TITLE
Assume unlabeled BMH are unscheduled

### ISSUE THREAD

**Issue by seaneagan** [airshipit/sip#7]
**Problem description (if applicable)**
Currently the SIP scheduling code identifies unscheduled BMH by looking for the following label:
`sip.airshipit.org/scheduled=false`

This means whoever is creating the BMH (e.g. Vino) would need to add this label, which is unnecessary, and creates tight coupling.

**Proposed change**

Update the SIP scheduling code to treat presence of the `sip.airshipit.org/scheduled` label, regardless of value as being scheduled, and absence of this label as unscheduled.

**Comment by seaneagan** [comment]
Actually we can probably just merge the `sip.airshipit.org/scheduled` and `sip.airshipit.org/workload-cluster` labels, and check for the presence/absence of the merged label e.g. `sip.airshipit.org/cluster: <namespace/name of SIPCluster>`

**Comment by seaneagan** [comment]
https://review.opendev.org/c/airship/sip/+/780302

**Comment by michaelfix** [comment]
@seaneagan - Sean, look like PS you have will close this issue, pending resolution to merge conflict(s) and reviews.  Thank you for your attention to this issue as it does need to close to meet EOM commitments.
